# Generated by Django 4.2.3 on 2024-10-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgdi_api', '0002_creator_contestant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('contestant', 'Contestant'), ('creator', 'Creator')], default='contestant', max_length=10),
        ),
    ]
