# Generated by Django 4.2.3 on 2024-10-22 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgdi_api', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgdi_api.creator')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='routes/')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgdi_api.creator')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/')),
                ('score', models.FloatField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgdi_api.competition')),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgdi_api.contestant')),
            ],
            options={
                'unique_together': {('contestant', 'competition')},
            },
        ),
        migrations.CreateModel(
            name='CompetitionRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgdi_api.competition')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgdi_api.route')),
            ],
            options={
                'unique_together': {('competition', 'route')},
            },
        ),
    ]
