version: "3.9"
services:
  frontend_pgdi:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    working_dir: '/app'
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules