version: "3.9"
services:

  backend:
    build:
      context: backend/.
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
      - ./backend/db.sqlite3:/code/db.sqlite3  #docker db is mounted on db.sqlite3 so it can be accessed both ways

  frontend_pgdi:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    working_dir: '/app'
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules